"""图表渲染样式常量。"""

# --- 线条宽度 ---
LINEWIDTH_ACTIVE = 2.8
LINEWIDTH_INACTIVE = 0.9
LINEWIDTH_DEFAULT = 1.4
LINEWIDTH_FIT_ACTIVE = 2.8
LINEWIDTH_FIT_INACTIVE = 1.0
LINEWIDTH_FIT_DEFAULT = 1.5

# --- 透明度 ---
ALPHA_ACTIVE = 1.0
ALPHA_INACTIVE = 0.32
ALPHA_DEFAULT = 0.86
ALPHA_SCATTER_SELECTED = 0.95
ALPHA_SCATTER_DESELECTED_ACTIVE = 0.35
ALPHA_SCATTER_DESELECTED_INACTIVE = 0.12
ALPHA_SCATTER_DESELECTED_DEFAULT = 0.25
ALPHA_SCATTER_NO_FIT_ACTIVE = 0.75
ALPHA_SCATTER_NO_FIT_INACTIVE = 0.2
ALPHA_SCATTER_NO_FIT_DEFAULT = 0.5
ALPHA_FIT_LINE_ACTIVE = 0.98
ALPHA_FIT_LINE_INACTIVE = 0.28
ALPHA_FIT_LINE_DEFAULT = 0.75

# --- 标记大小 ---
MARKERSIZE_ACTIVE = 4.8
MARKERSIZE_INACTIVE = 2.6
MARKERSIZE_DEFAULT = 3.0

# --- 散点大小 ---
SCATTER_FIT_SELECTED_ACTIVE = 46
SCATTER_FIT_SELECTED_DEFAULT = 28
SCATTER_FIT_SELECTED_INACTIVE = 20
SCATTER_FIT_DESELECTED_ACTIVE = 24
SCATTER_FIT_DESELECTED_DEFAULT = 16
SCATTER_FIT_DESELECTED_INACTIVE = 12
SCATTER_RAW_FIT_ACTIVE = 30
SCATTER_RAW_FIT_DEFAULT = 24
SCATTER_NO_FIT_ACTIVE = 28
SCATTER_NO_FIT_DEFAULT = 18
SCATTER_NO_FIT_INACTIVE = 14

# --- 边框宽度 ---
EDGEWIDTH_ACTIVE = 0.8
EDGEWIDTH_INACTIVE = 0.4

# --- 布局参数 ---
# LEFT 需要足够大，以容纳 CJK Y 轴标题文字；0.10 可在大多数窗口尺寸下防止截断
GRIDSPEC_WSPACE = 0.30
GRIDSPEC_LEFT = 0.10
GRIDSPEC_RIGHT = 0.97
GRIDSPEC_TOP = 0.92
GRIDSPEC_BOTTOM = 0.12

# --- 拟合线 ---
FIT_LINE_MARGIN_FRAC = 0.08
FIT_LINE_MARGIN_MIN = 0.02
FIT_LINE_POINTS = 100

# --- 字体大小 ---
FONTSIZE_TITLE = 12
FONTSIZE_LABEL = 11
FONTSIZE_LEGEND = 8
FONTSIZE_PLACEHOLDER = 16
